### ISSUE TITLE
Non-player specific binding?

### ISSUE THREAD

**Issue by wyozi** [Winded/BiValues#1]
This library seems really cool, but the functionality is pretty limited without ability to bind values to objects instead of player entities.

For example in one of my gamemodes I have a list of Area objects that are identified by a string id. I would love to do something like  `BiValues.New("area" .. area.id, "Example", {AutoApply = true, UseSync = true}, defaults);`.

I think it would actually be feasible to use string id for all BiValues. You could check if first argument to `BiValues.New` is a player, and if it is, convert it to something like `player:uid`, or even create dedicated constructor for players.

**Comment by Winded** [comment]
Containers are linked to players so that the synchronization knows what player to send the variables to. I could add support for just using nil so that the container is shared with all players, or pass multiple players in a table to share it with specific players. The second argument is the identifier of the container, so you could use `"area" .. area.id` on that one.

**Comment by wyozi** [comment]
Yeah, that'd work.

**Comment by Winded** [comment]
Added support for non-player specific containers and multiple players now.
